### ISSUE TITLE
Pixel-level populations can be hard to see

### ISSUE THREAD

**Issue by ngreenwald** [ParkerICI/mantis-viewer#62]
The colormap that is used for displaying pixel populations includes some colors that are quite dim. This can make it hard to see where on the image the given population is. For some reason, this doesn't seem to be happen with the cell-level populations. Maybe something about the brightness settings for cell segmentation populations is different, making them easier to see?

**Comment by rj3d** [comment]
The functionality that you're using to load and display pixel populations was originally intended for regions of interest on the image. Since these were intended for regions, the alpha of these objects is set to something like 60% so the underlying region and segments can be seen, and the alpha is increased to something like 80% when highlighted (e.g. moused over).

That being said, it's super cool what you've been using this feature to do! It would be great to improve it so that it works better for your use case. I'm imaging the easiest way to accomplish solving the problem you described would be to allow users to change the alpha of regions/pixel populations. I think the lowest effort way to achieve this would be to add a slider to the image controls to modify the global region/pixel population alpha. Would this work for you? Would there be another way that would work better for your use case?

**Comment by ngreenwald** [comment]
Yeah, if the only difference between the cell and region colormaps is the alpha then having the option to change it would definitely solve the issue

**Comment by rj3d** [comment]
Cool! I created a ticket to add that feature. It's on the shortlist of
things to get done in the next couple of weeks.

Rob Schiemann

Staff Software Engineer  I  Informatics

***@***.***


Follow us: Twitter <https://twitter.com/ParkerICI> | Facebook
<https://www.facebook.com/ParkerICI/> | LinkedIn
<https://www.linkedin.com/company/parker-institute-for-cancer-immunotherapy/>
 | Instagram <https://www.instagram.com/parkerici/>

**Comment by rj3d** [comment]
Feature added in 1.2.2-rc.4.
